<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<UserRuntimeConfig>runtimeconfig.template.json</UserRuntimeConfig>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="DotNetEnv" Version="3.1.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="xunit.v3" Version="2.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AccelByte.Extend.SimpleEOSMatchmaking.Server\AccelByte.Extend.SimpleEOSMatchmaking.Server.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>
